sudo: required
language: java
jdk:
- openjdk8
before_install:
- openssl aes-256-cbc -K $encrypted_a4e132a4b597_key -iv $encrypted_a4e132a4b597_iv
  -in travis/codesigning.asc.enc -out travis/codesigning.asc -d
- gpg --fast-import travis/codesigning.asc
script:
- "./gradlew check"
- "./gradlew build"
- |
  set -e
  if [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "master" ]; then
   ./gradlew publish --info
   ./gradlew getStagingProfile closeAndReleaseRepository --info
  fi
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
notifications:
  slack:
    secure: xarIqgqwazZl5wpwxKtgwcPTGWirNhTDpDiNwmnyxdtMD9tw38XySjifuFSCXJApF57dKlxiVT4K//AY8jBsLsSB/stng4nOg6fuEP/ZxDY5/C80CFHXltSYjDL1zDBBECw9gugOAvmMePGpRXY9Jm9sZgku7PYv+VA6FCOb2BnqELsxN7Hj/3Z9w67uosh5ytJ8sQ9aN6eAcnl4ST3O7cOH5zfiS4yzufAZ1oZjLkkXwSuPl5YN3rLusQVcjnKXg+fQ5qBfrtxM1+TRe0H8DQUfU+SiKF+QbvNx/XPQFIwlcVZ3o9KJ7AV9ANn5qmypx+u0UMOTPSshq3lE3GkNCWVuDLZ2Fm2XiFH8xxhPQpHLY77z7y+Yy6JSrRBtkBtlMksi3ghgCe7tJ/CXx/af2FPyHTaVSVXLJn7EhHsWxfCyrcMvaV0LqJNkfVeFveoHTSdh2+FSsSH8euI20QwlnVHY3jf+FtafZ5CxLkolFNX+QdHVMJj/h0iJxSiZl7cCu8KLuD/pezEH5a3hPzknkhcEF6EOvj2KvCWdQbcuo7eY0ORcDoaZN9CrFblh75FxQfyCKkRUvz0m+iiy6YNYWN6DpArie1YljX1HkBZypg172l05Ejxg4Dy9RjSJJcIVJb1z15OANIZ2+1/eHKBQWdWJfoAoFHUIfI2KCy5zYg4=
env:
  global:
  - GPG_KEY_NAME=navikt
  # GPG_PASSPHRASE
  - secure: Nn2GvbPA0+FBJVHCPiUAHbpZlQuEbzSZo9NashM+q4Q2qt4UO7iIs9nP601wXrS8O7SIObopEfvSgcJCflNiHYoaIBt0ZH6C0Wra9n18PIDlyS087hfvPVF3mpUE9S1PcobKnp9zkLg4FG8XDvGzJK1m7dl08Wn98KWPyEWe5gmDfvRa5njOyMZOeOYPO/fHRrFO+rqbO1AaMSGBDNMmC7DubnxIjgnk1bhqD0sUnRhhYCFqWPIJoYPiIdZkZrbymNI4NQ/6um+O+V6z0MmI1kXHQ/bLRAttEfekSD0sebPgfde4Xm7pOPxIY0u0I9vtHSddsySTN6tzx5Yl82JOHHpRh/pPln7v7FcbLiOr0nq3YDgq+5ikLgKwB1bGWYjcFRN+XQz1we8a31Yv1X91tJGNp40QdO/k3Rx/L48RecepG4XUmQ20ZXZ03+LaIXENBHW3xHSUJY0VxCihowTkv/DRyItwUrD1Nz3pEzZgq5D0IcYWSESu4VNalkiPrHBz/M8k+WoPQgyhFp9bRYvxnvfEwpva6B+XABmFMghgff9uTog8hqb0yhffY95b+sf7A8g82GWYQbaNKaxaQaKNl70bAn/L7YfVY+6TrY8/vwo2vmlEGc6bHhsMuPvUxpgHPEDxQ0QZJJQXipIfeF2d6+lDjs/XtvPbgCajRurE9zc=
  - OSSRH_JIRA_USERNAME=navikt
  # OSSRH_JIRA_PASSWORD
  - secure: Vp/P7TvFRXb46I7CoR5/yZEW1fOBs5N6oT3w3Ceks8+07MKygrrOvjHYkaQsj2tgruMFnsY5FeuxN+ZRRdjue5F1oc8ITnPdyqkAQ+xwqEFYA57eIoPuulA3yZo3xut9ZzVlkoFjJwZ3fkIIJI28toS1O4uozsa6rG5ksUYLDf8iSkcs1Qipez2szygaJhKAKIFOUhdrZZtOQQyeRHljc7GBENJqqsdTmnFDPeYBncTuyLnRUNH3KvT8Mm2szsHoKALd9luZNmRJvt7rqGQuLAaKI8MM5YHSHCvS78sLG+BHNmwakGhrzQLOjOd1dUPsCAlf8rKkZ1OPmK2YoBrWxXgo2JXAe3/8gMKDgI3H9MPp3Mn1xs0IGTlmjQMxajgM/GwbvXqtghSW+xwBCeTU/HxGtHMudFtTAwzxYPlZHu+gOyJRzatbNS9US68jmsV6FreZalhr0r4M2d5qU4DE4mKPJWnJeZOgJsZnbIw/uoPCBrHAJg7o1xVds6swp4q4tF41OlHjJOe5ZUOeZMWYd3GqzkyFKBvotfx7Gz8wAEpNIwWclwx4J9dqtNrhLrkFbZ1MDJGYdEGoALliJ2OzMOCALMvQ8eUKlMtS6faYGZR2G5oku8hf9Tm2rBVppNpyVoS1aWPM8BKmEsDEniaT3RF3Pmt/vDvv9MyTaEjA2BY=
