sudo: required
language: java
jdk:
- openjdk8
before_install:
- openssl aes-256-cbc -K $encrypted_a4e132a4b597_key -iv $encrypted_a4e132a4b597_iv
  -in travis/codesigning.asc.enc -out travis/codesigning.asc -d
script:
- "./mvnw clean install"
- |
  set -e
  if [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "master" ]; then
     echo "Importing GPG key into keyring"
     gpg --fast-import travis/codesigning.asc
     echo "Running release"
     ./mvnw --settings travis/settings.xml deploy -Prelease -DskipTests=true
  fi
cache:
  directories:
  - "$HOME/.m2"
notifications:
  slack:
    secure: xarIqgqwazZl5wpwxKtgwcPTGWirNhTDpDiNwmnyxdtMD9tw38XySjifuFSCXJApF57dKlxiVT4K//AY8jBsLsSB/stng4nOg6fuEP/ZxDY5/C80CFHXltSYjDL1zDBBECw9gugOAvmMePGpRXY9Jm9sZgku7PYv+VA6FCOb2BnqELsxN7Hj/3Z9w67uosh5ytJ8sQ9aN6eAcnl4ST3O7cOH5zfiS4yzufAZ1oZjLkkXwSuPl5YN3rLusQVcjnKXg+fQ5qBfrtxM1+TRe0H8DQUfU+SiKF+QbvNx/XPQFIwlcVZ3o9KJ7AV9ANn5qmypx+u0UMOTPSshq3lE3GkNCWVuDLZ2Fm2XiFH8xxhPQpHLY77z7y+Yy6JSrRBtkBtlMksi3ghgCe7tJ/CXx/af2FPyHTaVSVXLJn7EhHsWxfCyrcMvaV0LqJNkfVeFveoHTSdh2+FSsSH8euI20QwlnVHY3jf+FtafZ5CxLkolFNX+QdHVMJj/h0iJxSiZl7cCu8KLuD/pezEH5a3hPzknkhcEF6EOvj2KvCWdQbcuo7eY0ORcDoaZN9CrFblh75FxQfyCKkRUvz0m+iiy6YNYWN6DpArie1YljX1HkBZypg172l05Ejxg4Dy9RjSJJcIVJb1z15OANIZ2+1/eHKBQWdWJfoAoFHUIfI2KCy5zYg4=
env:
  global:
  - GPG_KEY_NAME=navikt
  - secure: Nn2GvbPA0+FBJVHCPiUAHbpZlQuEbzSZo9NashM+q4Q2qt4UO7iIs9nP601wXrS8O7SIObopEfvSgcJCflNiHYoaIBt0ZH6C0Wra9n18PIDlyS087hfvPVF3mpUE9S1PcobKnp9zkLg4FG8XDvGzJK1m7dl08Wn98KWPyEWe5gmDfvRa5njOyMZOeOYPO/fHRrFO+rqbO1AaMSGBDNMmC7DubnxIjgnk1bhqD0sUnRhhYCFqWPIJoYPiIdZkZrbymNI4NQ/6um+O+V6z0MmI1kXHQ/bLRAttEfekSD0sebPgfde4Xm7pOPxIY0u0I9vtHSddsySTN6tzx5Yl82JOHHpRh/pPln7v7FcbLiOr0nq3YDgq+5ikLgKwB1bGWYjcFRN+XQz1we8a31Yv1X91tJGNp40QdO/k3Rx/L48RecepG4XUmQ20ZXZ03+LaIXENBHW3xHSUJY0VxCihowTkv/DRyItwUrD1Nz3pEzZgq5D0IcYWSESu4VNalkiPrHBz/M8k+WoPQgyhFp9bRYvxnvfEwpva6B+XABmFMghgff9uTog8hqb0yhffY95b+sf7A8g82GWYQbaNKaxaQaKNl70bAn/L7YfVY+6TrY8/vwo2vmlEGc6bHhsMuPvUxpgHPEDxQ0QZJJQXipIfeF2d6+lDjs/XtvPbgCajRurE9zc=
  - OSSRH_JIRA_USERNAME=navikt
  - secure: qts4sIKmzNyjdjSNn9ijuSAP2ipbNWM8uupt4ZapI6mR3hk5rnG/NjoehmeOxnLyoGOQHrmRe4KCrLmX7YAskEjUHa4laRqcZi0SaQcGLM0ve3NukLRLz14wAviDn9ES819Ac+ieadtNwLeeBQBdCmQKEhAe2uKC246rICvYJlKh2aUkuBoqbHhkBgYmWTA0y2sXK0Ut5OXddaFmJmjXj6TiH4sbSdAUbfhoR95mBaVtNuJyJ6fGvj07h8qds5qXzt0B3nOxLzRcBGDAy3NqYZQkBwHLVcVtuQktHBzvFjGMazSDl759xYbv/Fu60dxEFsNIFCkP4+lRBnpy9PgcHNnX3Z5ZddYdqKGXJksexj93H78460MooXYjiXb2ICYxB7TaEIgrVHJTunvPUNkkaQOq9m47CUUXZDTHdiAodjGGs4zbhgG78x1cj/TPZ9F0mPupUe2HluLMRiHWry1fxdCEkJ4OOWEdpvbCLSiT5IjQ+g/FyVkeL5l3RUtHDhXj8LbZN0dYY78YgvMS5hnbY+ZBgSMTWDzt99z3Y6SdLkfnoX6dff6hx835mCTMx3TD8BPflN+yAVV8iE9vsjmogl5pQPltJtAbPUDckm+8KlFesbnqe1hmRP3zcw0aUzaCMHBiSUaRIOd9I3rwvxAz0z7UBSO04X6hvXNkswykzyI=
